from datetime import date

my_blogs = [
    {"id": 1, "title": "The Rise of AI", "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", "is_published": True, "created_by": 1, "created_at": date(2024, 11, 20), "updated_at": date(2024, 11, 21), "is_deleted": False, "rating": 4},
    {"id": 2, "title": "Future of Web Development", "content": "Nulla convallis leo in ante posuere, ac suscipit lorem vestibulum.", "is_published": True, "created_by": 2, "created_at": date(2024, 11, 18), "updated_at": date(2024, 11, 19), "is_deleted": False, "rating": 5},
    {"id": 3, "title": "Exploring the Unknown", "content": "Donec auctor eros at ante faucibus, ac consequat mi mollis.", "is_published": True, "created_by": 3, "created_at": date(2024, 11, 15), "updated_at": date(2024, 11, 16), "is_deleted": False, "rating": None},
    {"id": 4, "title": "Tech Trends in 2024", "content": "Curabitur nec ipsum ut ipsum ullamcorper laoreet.", "is_published": True, "created_by": 4, "created_at": date(2024, 11, 10), "updated_at": date(2024, 11, 12), "is_deleted": False, "rating": 3},
    {"id": 5, "title": "React vs Vue: The Ultimate Showdown", "content": "Praesent et nisi tristique, mollis sem sed, tempus lorem.", "is_published": True, "created_by": 5, "created_at": date(2024, 11, 1), "updated_at": date(2024, 11, 5), "is_deleted": False, "rating": 4},
    {"id": 6, "title": "Understanding Python", "content": "Vestibulum vehicula mauris eu risus pretium, ac fermentum nulla suscipit.", "is_published": True, "created_by": 6, "created_at": date(2024, 10, 25), "updated_at": date(2024, 10, 26), "is_deleted": False, "rating": 5},
    {"id": 7, "title": "Building a Portfolio", "content": "Aliquam erat volutpat. Vivamus sit amet libero id augue consequat dictum.", "is_published": True, "created_by": 7, "created_at": date(2024, 10, 20), "updated_at": date(2024, 10, 22), "is_deleted": False, "rating": 2},
    {"id": 8, "title": "Designing for the Web", "content": "Quisque tincidunt felis ac risus dictum, a posuere nulla ornare.", "is_published": True, "created_by": 8, "created_at": date(2024, 10, 15), "updated_at": date(2024, 10, 16), "is_deleted": False, "rating": None},
    {"id": 9, "title": "Introduction to Django", "content": "Sed vel justo in dui fringilla vestibulum ac in ante.", "is_published": True, "created_by": 9, "created_at": date(2024, 10, 10), "updated_at": date(2024, 10, 12), "is_deleted": False, "rating": 3},
    {"id": 10, "title": "The Power of TypeScript", "content": "Duis auctor felis at diam fermentum, eget ultricies nisl placerat.", "is_published": True, "created_by": 10, "created_at": date(2024, 10, 5), "updated_at": date(2024, 10, 7), "is_deleted": False, "rating": 4},
    {"id": 11, "title": "Machine Learning Basics", "content": "Vestibulum id nisl non libero dictum malesuada.", "is_published": True, "created_by": 1, "created_at": date(2024, 9, 30), "updated_at": date(2024, 10, 1), "is_deleted": False, "rating": None},
    {"id": 12, "title": "React Best Practices", "content": "Sed non ipsum at dui mollis egestas.", "is_published": True, "created_by": 2, "created_at": date(2024, 9, 25), "updated_at": date(2024, 9, 26), "is_deleted": False, "rating": 5},
    {"id": 13, "title": "The Role of Databases", "content": "Donec sollicitudin turpis ut facilisis dapibus.", "is_published": True, "created_by": 3, "created_at": date(2024, 9, 20), "updated_at": date(2024, 9, 21), "is_deleted": False, "rating": 3},
    {"id": 14, "title": "Advanced JavaScript", "content": "Suspendisse sed nulla a neque fermentum vulputate.", "is_published": True, "created_by": 4, "created_at": date(2024, 9, 15), "updated_at": date(2024, 9, 16), "is_deleted": False, "rating": 4},
    {"id": 15, "title": "Why Choose Python?", "content": "Vestibulum pretium velit id erat consectetur, nec tincidunt orci aliquam.", "is_published": True, "created_by": 5, "created_at": date(2024, 9, 10), "updated_at": date(2024, 9, 12), "is_deleted": False, "rating": None},
    {"id": 16, "title": "Web Security 101", "content": "Cras eget mi gravida, eleifend lectus vitae, suscipit justo.", "is_published": True, "created_by": 6, "created_at": date(2024, 9, 5), "updated_at": date(2024, 9, 6), "is_deleted": False, "rating": 2},
    {"id": 17, "title": "Responsive Design Principles", "content": "Integer faucibus dui eget dolor rutrum, sed sollicitudin arcu interdum.", "is_published": True, "created_by": 7, "created_at": date(2024, 9, 1), "updated_at": date(2024, 9, 2), "is_deleted": False, "rating": 5},
    {"id": 18, "title": "Why Automation Matters", "content": "Ut cursus purus eget dolor volutpat, sit amet pretium ante luctus.", "is_published": True, "created_by": 8, "created_at": date(2024, 8, 25), "updated_at": date(2024, 8, 26), "is_deleted": False, "rating": None},
    {"id": 19, "title": "The Evolution of the Internet", "content": "Nullam at urna ac arcu fringilla porttitor.", "is_published": True, "created_by": 9, "created_at": date(2024, 8, 20), "updated_at": date(2024, 8, 22), "is_deleted": False, "rating": 3},
    {"id": 20, "title": "Exploring Blockchain", "content": "Fusce auctor mauris vitae erat fermentum, sit amet ultricies arcu fermentum.", "is_published": True, "created_by": 10, "created_at": date(2024, 8, 15), "updated_at": date(2024, 8, 16), "is_deleted": False, "rating": 4}
]

